// Mocks generated by Mockito 5.4.6 from annotations
// in zenu/test/services/reminder_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:zenu/l10n/app_localizations.dart' as _i4;
import 'package:zenu/models/reminder.dart' as _i7;
import 'package:zenu/models/statistics.dart' as _i2;
import 'package:zenu/services/data_service.dart' as _i8;
import 'package:zenu/services/notification_service.dart' as _i3;
import 'package:zenu/services/reminder_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatistics_0 extends _i1.SmartFake implements _i2.Statistics {
  _FakeStatistics_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i3.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setLocalizations(_i4.AppLocalizations? localizations) =>
      super.noSuchMethod(
        Invocation.method(#setLocalizations, [localizations]),
        returnValueForMissingStub: null,
      );

  @override
  void setReminderService(_i5.ReminderService? reminderService) =>
      super.noSuchMethod(
        Invocation.method(#setReminderService, [reminderService]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> showReminderNotification(_i7.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#showReminderNotification, [reminder]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i8.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<Map<String, dynamic>>> loadReminders() =>
      (super.noSuchMethod(
            Invocation.method(#loadReminders, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> saveReminders(List<_i7.Reminder>? reminders) =>
      (super.noSuchMethod(
            Invocation.method(#saveReminders, [reminders]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Statistics> loadStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#loadStatistics, []),
            returnValue: _i6.Future<_i2.Statistics>.value(
              _FakeStatistics_0(this, Invocation.method(#loadStatistics, [])),
            ),
          )
          as _i6.Future<_i2.Statistics>);

  @override
  _i6.Future<void> saveStatistics(_i2.Statistics? statistics) =>
      (super.noSuchMethod(
            Invocation.method(#saveStatistics, [statistics]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getCacheStats, []),
            ),
          )
          as String);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
